
import com.sun.org.apache.bcel.internal.generic.BREAKPOINT;
import java.awt.ComponentOrientation;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author huyng
 */
public class Bangchudon extends javax.swing.JFrame {

    /**
     * Creates new form Bangchudon
     */
    public Bangchudon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ranDomkey = new javax.swing.JButton();
        encrypTion = new javax.swing.JButton();
        dencrypTion = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bảng chữ đơn");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("key");

        jLabel2.setText("key");

        ranDomkey.setText("Random Key");
        ranDomkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranDomkeyActionPerformed(evt);
            }
        });

        encrypTion.setText("Encryption");
        encrypTion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypTionActionPerformed(evt);
            }
        });

        dencrypTion.setText("Decryption");
        dencrypTion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dencrypTionActionPerformed(evt);
            }
        });

        textField1.setEnabled(false);
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        textField2.setEnabled(false);

        textField3.setEditable(false);
        textField3.setText("abcdefghijklmnopqrstuvwxyz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dencrypTion)
                            .addComponent(encrypTion)
                            .addComponent(ranDomkey, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(ranDomkey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(encrypTion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(dencrypTion)
                        .addGap(82, 82, 82))))
        );

        ranDomkey.getAccessibleContext().setAccessibleName("jButton2");
        dencrypTion.getAccessibleContext().setAccessibleName("jButton3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ranDomkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranDomkeyActionPerformed
        // TODO add your handling code here:
        String keyCore="abcdefghijklmnopqrstuvwxyz";//Khởi tạo bảng mã ASCII
        
        Random ranDom=new Random();//Khởi tạo 1 biến để chứa các chữ số random
        String after ="";
        for (int i = 0; i < keyCore.length(); i++) {//sử dụng vòng lặp
            int index =ranDom.nextInt(keyCore.length());//tạo 1 biến là kết quả từ việc 
                                            //lấy những con số ngẫu nhiên ở tại chuỗi string keycore đã khai báo
            char ramChar =keyCore.charAt(index);//trả về chữ có vị trí tương ứng với index
            
            if (after.indexOf(ramChar)==-1)//nếu chữ cái nằm trong khoảng của ramChar sẽ trả về -1
            {
                after+=ramChar;
            }
            else{ // nếu ko tìm tiếp
                i--;
            }
        }
       
        //Xuất ra màn hình
        textField1.setText(after);
        textField2.setText(after);
    }//GEN-LAST:event_ranDomkeyActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
                // TODO add your handling code here:
            if (!textField1.getText().isEmpty()) //trường hợp nếu textField1 không trống
            {
                textField2.setText(textField1.getText());
            }
            else if (textField1.getText().length()<26) //trường hợp nếu textField1 lớn hơn 26 ký tự
            {
               JOptionPane.showMessageDialog(null, "Phải đủ 26 chữ cái xin mời nhập lại");
             }
    }//GEN-LAST:event_textField1ActionPerformed

    private void encrypTionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypTionActionPerformed
        // TODO add your handling code here:
        String ASCII = "abcdefghijklmnopqrstuvwxyz";//Khởi tạo chuỗi ASCII
        String plainText = jTextArea2.getText(); //Lấy giá trị của jTextArea2
        String key = textField1.getText(); //Lấy giá trị của textField1
        plainText = plainText.toLowerCase(); //Chuyển plainText thành chữ thường
        String encrypTion = ""; //Biến lưu kết quả
        //Vì phương thức này nếu plainText rỗng sẽ không thể thực hiện được nên sẽ bắt lỗi và dừng chương trình
        if(plainText.isEmpty()){
            return;
        }
        for(int i = 0; i< plainText.length();i++){ 
            int positionText = ASCII.indexOf(plainText.charAt(i));//Khởi tạo biến dùng để tìm vị trí của từng chữ trong plaintext
            char after = key.charAt(positionText); //Khởi tạo biến dùng để chứa vị trí của chữ đã tìm được 
            encrypTion += after;//lưu vào biến encrytion để xuất ra màn hình
        }
        
        //Xuất ra màn hình
        jTextArea1.setText(encrypTion);
        jTextArea2.setText("");
    }//GEN-LAST:event_encrypTionActionPerformed

    private void dencrypTionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dencrypTionActionPerformed
        // TODO add your handling code here:
        
         String ASCII = "abcdefghijklmnopqrstuvwxyz";
        String plainText = jTextArea1.getText(); //Lấy value của plainText
        String key = textField2.getText(); //Lấy value của key
        plainText = plainText.toLowerCase(); //Chuyển plainText thành chữ thường
        String dencrypTion = ""; //Biến lưu kết quả
        //Vì phương thức này nếu plainText rỗng sẽ không thể thực hiện được nên sẽ bắt lỗi và dừng chương trình
        if(plainText.isEmpty()){
            return;
        }
        //Tương tự như trên
        for(int i = 0; i< plainText.length();i++){ 
            int positionText = key.indexOf(plainText.charAt(i));
            char after = ASCII.charAt(positionText);
            dencrypTion += after;
        }
        jTextArea2.setText(dencrypTion);
        jTextArea1.setText("");
    }//GEN-LAST:event_dencrypTionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bangchudon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bangchudon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bangchudon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bangchudon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bangchudon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dencrypTion;
    private javax.swing.JButton encrypTion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton ranDomkey;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
