/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuyendichdong;

/**
 *
 * @author phat
 */
public class ChuyenDong extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenDong
     */
    public ChuyenDong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chuyen Dich Dong");

        jLabel1.setText("PlainText");

        jLabel2.setText("CipherText");

        jButton1.setText("Encryption");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Decryption");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear Code");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Key");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2)
                                            .addGap(9, 9, 9))))))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(162, 162, 162))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)))
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String key = jTextField3.getText();
        key = deleteSpace(key);

        String plainText = jTextField1.getText();
        plainText = deleteSpace(plainText);
        int[] numKey = keyWord(key);

        int residualcheck = plainText.length() % key.length(); // kiem tra co du khong
        int dummyCharacters = key.length() - residualcheck; // lay key tru cho so du de coi them bao nhieu ky tu cho bang cot theo key
        if (residualcheck != 0) {
            for (int i = 0; i < dummyCharacters; i++) {
                plainText += "z";
            }
        }

        int numRow = plainText.length() / key.length(); //sau khi them ky tu / cho key de xem tao ra bao nhieu dong
        char[][] arr = new char[numRow][key.length()];
        int z = 0;
        for (int i = 0; i < numRow; i++) {                    //them cac ki tu plaintext vao ma tran
            for (int j = 0; j < key.length(); j++) {
                arr[i][j] = plainText.charAt(z++);
            }
        }

        String cipherText = "";//tao chuoi rong
        String numLoc = getNumber(key, numKey);
        int num = 0;//tao bien n voi gia tri = 0
        for (int i = 0; i < key.length(); i++) { //Duyet theo cot
            int d;
            if (num == key.length()) { //neu k = do dai key thi thoat vong lap
                break;
            } else {
                d = Character.getNumericValue(numLoc.charAt(num++));//Character.getNumericValue chuyen tu dang chu => so

            }
            for (int j = 0; j < numRow; j++) { //Them ki tu vao chuoi rong theo cot
                cipherText += arr[j][d];
            }
        }
        jTextField2.setText(cipherText);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cipherText = jTextField2.getText();
        cipherText = deleteSpace(cipherText);
        String key = jTextField3.getText();
        key = deleteSpace(key);
        int numRow = cipherText.length() / key.length(); //tao so dong
        char[][] arr = new char[numRow][key.length()];
        int[] numList = keyWord(key);
        String numLoc = getNumber(key, numList);
        for (int i = 0, k = 0; i < cipherText.length(); i++) { //khoi tao for theo do dai cua cipherText va khoi tao k = 0;
            int d = 0;//dung de gan so k
            if (k == key.length()) {
                k = 0;
            } else {
                d = Character.getNumericValue(numLoc.charAt(k++)); //Dung phuong thuc de chuyen ki tu trong ham numLoc sang int
            }

            for (int j = 0; j < numRow; j++) { //Them ki tu vao ma tran tu vi tri chu nho nhat den tang dan

                arr[j][d] = cipherText.charAt(i++);
            }
            --i;
        }
        String plainText = "";//Tao chuoi rong
        for (int i = 0; i < numRow; i++) { //Duyet dong
            for (int j = 0; j < key.length(); j++) {//Duyet cot
                plainText += arr[i][j];//Them ki tu da duyet tu dong va cot them vao chuoi
            }
        }
        jTextField1.setText(plainText);
        jTextField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenDong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenDong().setVisible(true);
            }
        });
    }

    public static int[] keyWord(String key)//mang theo bang chu cai tai phan tu mang vi du tu hello => 2 1 3 4 5
    {
        String alpha = "abcdefghijklmnopqrstuvwxyz"; //tao bang chu cai tu a-z
        int[] numList = new int[key.length()]; //mang do dai cua mang tu key
        int a = 0;
        for (int i = 0; i < alpha.length(); i++) {
            for (int j = 0; j < key.length(); j++) {
                if (alpha.charAt(i) == key.charAt(j)) { //neu ma chu cai do == chu cai trong key   
                    a++;
                    numList[j] = a; //gan phan tu do = a
                    //sau do tang len 1
                }
            }
        }
        return numList;
    }

    public static String getNumber(String key, int[] numList)// chuoi dung de sap xep phan tu tu ham keyword
    {
        String a = "";//tao chuoi rong

        for (int i = 0; i < key.length() + 1; i++) { //cong them 1 vi trong ham keyWord t chay tu 1-n
            for (int j = 0; j < key.length(); j++) {
                if (numList[j] == i) { // tu trong numList tao tren ta dung 2 vong lap de dim phan tu numList == i 
                    a += j;//sau do gan vi tri tim duoc vao a

                }
            }
        }
        return a;
    }

    public static String deleteSpace(String text) {
        text = text.toLowerCase();
        text = text.replace(" ", "");
        String result = "";//tạo chuỗi rỗng
        for (int i = 0; i < text.length(); i++) { // dùng vòng lặp for để duyệt lấy kí tự
            char c = text.charAt(i); //dùng kiểu dữ liệu char để lấy một kí tự trong chuỗi string dùng charAt
            if (Character.isLetter(c)) { // kiểm tra có phải là kí tự không
                result += c; // nếu là kí tự thì thêm vào chuỗi
            }
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
